FROM circleci/android:api-26-alpha

RUN sudo apt-get update
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN sudo apt-get install ruby-full
RUN sudo apt-get install build-essential

RUN sudo gem install fastlane
RUN sudo gem cleanup
RUN fastlane action setup_circle_ci
RUN sudo npm install -g cordova

RUN sdkmanager "system-images;android-22;default;armeabi-v7a"
RUN echo "no" | avdmanager create avd -n test22 -k "system-images;android-22;default;armeabi-v7a"

RUN sdkmanager "system-images;android-24;google_apis;armeabi-v7a"
RUN echo "no" | avdmanager create avd -n test24 -k "system-images;android-24;google_apis;armeabi-v7a"

RUN sdkmanager "build-tools;26.0.1"
RUN sdkmanager "extras;android;m2repository"
